rootPath = ../../
include ${rootPath}/assemblathon1/include.mk
assembliesDir=${dataPath}/assemblathon1/scaffolds
outputDir=${outputPath}/assemblathon1/static

configFile=${libPath}/config_static.xml

all : basic

clean :
	rm -rf ${outputDir}/*
