rootPath = ../..
include ${rootPath}/assemblathon1/include.mk
assembliesDir=${dataPath}/assemblathon1/contigs
outputDir=${outputPath}/assemblathon1/contigs

all : basic

clean :
	rm -rf ${outputDir}/*
