rootPath = ../..
include ${rootPath}/tests/include.mk

assembliesDir=${dataPath}/tests/little
outputDir=${outputPath}/tests/static

configFile=${libPath}/config_static.xml

all : basic

clean :
	rm -rf ${outputDir}/*

