rootPath = ../../
include ${rootPath}/tests/include.mk

haplotypeSequences=${dataPath}/assemblathon1/simulatedHaplotypes/hap1.trf.repmask.fa.complete ${dataPath}/assemblathon1/simulatedHaplotypes/hap2.trf.repmask.fa.complete ${dataPath}/assemblathon1/simulatedHaplotypes/Escherichia_coliO83_H1_1.trf.repmask.fa.complete
assembliesDir=${dataPath}/tests/big
outputDir=${outputPath}/tests/big

include ${rootPath}include.mk

all : basic

clean :
	rm -rf ${outputDir}/*

